Import('env', 'object_files')

src = [
    "ClientService.cc",
    "ControlService.cc",
    "Globals.cc",
    "RaftService.cc",
    "ServerStats.cc",
    "StateMachine.cc",
]
object_files['Server'] = (env.StaticObject(src) +
                          env.Protobuf("SnapshotStateMachine.proto"))
